version: "3.7"

services:
  https-proxy:
    image: caddy:latest
    container_name: frappe-https-proxy
    restart: unless-stopped
    command: caddy reverse-proxy --from ${DOMAIN} --to ${DOMAIN}:7000
    volumes:
      - ./caddy:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
