name: Get public ip and details 
on:
  workflow_dispatch:
    inputs:
      Company:
        required: true
        description: Company

jobs:
  deploy:
    name: Get public ip
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::734522607489:role/github-action
        aws-region: ap-south-1
    - name: Create Instance
      run: |
        aws ec2 describe-instances --filters "Name=tag:Name,Values=${{ inputs.Company }}-hrms-ec2" --query "Reservations[].Instances[].PublicIpAddress" --output json