name: Enable HTTPS
on:
  workflow_dispatch:
    inputs:
      Company:
        required: true
        description: Company

      Domain:
        required: true
        description: Domain        

jobs:
  deploy:
    name: Get public ip
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::734522607489:role/github-action
        aws-region: ap-south-1
    - name: Build & Deploy
      env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME: ""
          USER_NAME: ubuntu
    
      run: |
        export pIP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${{ inputs.Company }}-hrms-ec2" --query "Reservations[].Instances[].PublicIpAddress" --output json)
        echo "please configure "$publicIP " on your domain ${{ Domain }}!!!!!!" 
        echo "Host Name=$pIP"
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@$pIP "cd frappe-hrms/scripts && chmod +x * && ./make_https.sh ${{ inputs.Domain }}"