name: Install Frappe App on ready server
on:
  workflow_dispatch:
    inputs:
      IP:
        required: true
        description: IP
      User:
        required: true
        description: User 
      Password:
        required: true
        description: Password                
      Domain:
        required: true
        description: Domain  
      frappeApp:
        type: choice
        description: Select frappe app
        options:
          - hrms
          - helth
          - helpdesk           
jobs:
  deploy:
    name: Install Frappe App on Server
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: SSH and run commands
      env: 
        Domain: ${{ inputs.Domain }}
        App: ${{ inputs.frappeApp }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.IP }}
        username: ${{ inputs.User }}
        password: ${{ inputs.Password}}
        port: 22
        script: |
         curl -O "https://raw.githubusercontent.com/argadepp/frappe-hrms/master/scripts/install_${{ inputs.frappeApp}}.sh"
         curl -O https://raw.githubusercontent.com/argadepp/frappe-hrms/master/common_site_config.json
         curl -O https://raw.githubusercontent.com/argadepp/frappe-hrms/master/docker-compose.yaml
         chmod +x *
         "./install_${{ inputs.frappeApp}}.sh $Domain $App"


