name: Install Frappe App on ready server
on:
  workflow_dispatch:
    inputs:
      IP:
        required: true
        description: IP
      User:
        required: true
        description: User 
      Password:
        required: true
        description: Password                
      Domain:
        required: true
        description: Domain  
      frappeApp:
        type: choice
        description: Select frappe app
        options:
          - hrms
          - helth
          - helpdesk           
jobs:
  deploy:
    name: Install Frappe App on Server
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.IP }}
        username: ${{ inputs.User }}
        password: ${{ inputs.Password }}
        port: 22
        source: "scripts/install_${{ inputs.frappeApp }}.sh"
        target: "/home/${{ inputes.User }}"

    - name: SSH and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.IP }}
        username: ${{ inputs.User }}
        password: ${{ inputs.Password}}
        port: 22
        script: |
          "cat /home/${{ inputes.User }}/install_${{ inputs.frappeApp }}.sh"   


